#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

rm -rf "$SPKG_LOCAL"/lib/python/site-packages/matplotlib
python setup.py install
