#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

# remove existing install
rm -rf "$SPKG_LOCAL"/lib/python/site-packages/matplotlib
rm -rf "$SPKG_LOCAL"/lib/python/site-packages/matplotlib*.egg-info
rm -rf "$SPKG_LOCAL"/lib/python/site-packages/mpl_toolkits
rm -f "$SPKG_LOCAL"/lib/python/site-packages/pylab.py
rm -f "$SPKG_LOCAL"/lib/python/site-packages/pylab.pyc

# select SPKG_LOCAL as basedirlist

echo "[directories]" > setup.cfg
echo "basedirlist = $SPKG_LOCAL" >> setup.cfg

if [ $(uname) = "Darwin" ]; then
    export PREFIX="$SPKG_LOCAL"
    # We use make.osx, which sets bunch of environment variables that are
    # needed on OSX
    # dont' set ARCH_FLAGS
    sed -i .bak "s/^ARCH_FLAGS/#ARCH_FLAGS/" make.osx
    # setup.py build:
    make -f make.osx mpl_build
    # setup.py install:
    make -f make.osx mpl_install
else
    python setup.py install
fi
